version: '3'
services:
  openldap:
    container_name: openldap
    build: ./LDAP-Dockerized-CentOS  # NEU: Sagt Docker, er soll den Container aus diesem Ordner bauen
    ports:
      - "389:389"

  shibboleth-idp:
    container_name: shibboleth-idp
    build: ./shibboleth-idp-dockerized # NEU: Sagt Docker, er soll den Container aus diesem Ordner bauen
    ports:
      - "443:4443"
      - "8443:8443"
      - "80:8080"
    volumes:
      - "./shibboleth-idp-dockerized/ext-conf:/opt/shibboleth-idp-ext-conf"
    environment:
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=12345"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=abcde"
    links:
      - "openldap:openldap"

  shibboleth-sp:
    container_name: shibboleth-sp
    build: ./shibboleth-sp-testapp   # NEU: Sagt Docker, er soll den Container aus diesem Ordner bauen
    ports:
      - "2080:80"
      - "2443:443"